In [69]:
# numpy - Numerical Python.
import numpy as np
arr = np.array([7,5,8,6,4,1.7,3])
arr.dtype

dtype('float64')

In [231]:
#multidimensional arrays
arr_2d = np.array([[23,54,32,],[14,44,25],[65,99,11]])
print("Dimension :", arr_2d.ndim)
print("Value of the num in first row and first col :",arr_2d[1,1])
print("Size of the array :",arr_2d.size)

Dimension : 2
Value of the num in first row and first col : 44
Size of the array : 9


In [79]:
#numerical operations using numpy
arr1 = np.array([2000,7000,9000,1000])
arr2 = np.array([300,400,350,700])
print(arr1+arr2)
arr1.ndim
arr1.size

[2300 7400 9350 1700]


4

In [213]:
a = np.array([30,68,27,94,55,70,10,48,86])
a[0:3:2]

array([30, 27])

In [211]:
Matrix = np.array([[5,3,2],
                  [7,9,4],
                  [1,6,8]])
Matrix[0:2,0:2]

array([[5, 3],
       [7, 9]])

In [305]:
ran_arr = np.arange(1,100,3)
ran_arr

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [307]:
lin_arr = np.linspace(1,10,10)
lin_arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [362]:
ones = np.ones((5,5),dtype = np.int32)
ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [364]:
zeros = np.zeros((3,3), dtype = np.int32)
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [366]:
ones[1:4,1:4] = zeros
ones

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [368]:
ones[2,2] = 8
ones

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 8, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [370]:
print(ones.sum())
print(ones.mean())
print(ones.min())
print(ones.max())
print(ones.std())

24
0.96
0
8
1.5094369811290567


In [7]:
#PANDAS LIBRARY
import pandas as pd
data = {
    'id' : [1,2,3,4,5,6,7],
    'name':['a','b','c','d','e','f','g'],
    'age': [22,24,34,32,54,44,27],
    'loc': ['Py','Py','Tn','Py','Tn','Py','Py',],
    'salary':[30000,40000,30000,1000000,500000,500000,40000]
}
dataframe = pd.DataFrame(data)
print(dataframe)
dataframe.shape

   id name  age loc   salary
0   1    a   22  Py    30000
1   2    b   24  Py    40000
2   3    c   34  Tn    30000
3   4    d   32  Py  1000000
4   5    e   54  Tn   500000
5   6    f   44  Py   500000
6   7    g   27  Py    40000


(7, 5)

In [402]:
dataframe.head(7)

id name  age loc   salary
0   1    a   22  Py    30000
1   2    b   24  Py    40000
2   3    c   34  Tn    30000
3   4    d   32  Py  1000000
4   5    e   54  Tn   500000
5   6    f   44  Py   500000
6   7    g   27  Py    40000

In [390]:
dataframe.tail(2)

id name  age loc  salary
5   6    f   44  Py  500000
6   7    g   27  Py   40000

In [9]:
dataframe.describe()

id        age          salary
count  7.000000   7.000000        7.000000
mean   4.000000  33.857143   305714.285714
std    2.160247  11.524301   376557.084776
min    1.000000  22.000000    30000.000000
25%    2.500000  25.500000    35000.000000
50%    4.000000  32.000000    40000.000000
75%    5.500000  39.000000   500000.000000
max    7.000000  54.000000  1000000.000000

In [11]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      7 non-null      int64 
 1   name    7 non-null      object
 2   age     7 non-null      int64 
 3   loc     7 non-null      object
 4   salary  7 non-null      int64 
dtypes: int64(3), object(2)
memory usage: 412.0+ bytes
